version: '3.9'

services:
  build:
    container_name: my-awesome-app-prod-ays
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/app/node_modules'
      - './:/app'
    ports:
      - "8080:8080"